sudo: false
addons:
  apt:
    packages:
      - libgd2-xpm-dev
      - graphviz
      - libxml2-dev
language: perl
perl:
  - "blead"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8"
env:
  global:
    - COVERAGE=1
    - DBICTEST_PG_DSN=dbi:Pg:dbname=sqlt_test
    - DBICTEST_PG_USER=postgres
matrix:
  allow_failures:
    - perl: "blead"
before_install:
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init
  - build-perl
  - perl -V
  - build-dist
  - cd $BUILD_DIR             # $BUILD_DIR is set by the build-dist command
install:
  - cpan-install --deps CGI DBD::SQLite XML::Parser DBD::Pg # Optional test deps
  - cpan-install Test::EOL Test::NoTabs # Author test deps
  - cpan-install --coverage
before_script:
  - psql -U postgres -c 'create database sqlt_test;'
  - coverage-setup
script:
  - perl Makefile.PL
  - prove -lrsv $(test-dirs)
after_success:
  - coverage-report
